spring:
  data:
    mongodb:
      uri: mongodb://todo:123456@mongo-todo-list:27017/todo?authSource=todo&authMechanism=SCRAM-SHA-1
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:todo-list.pub
