# This is a basic workflow to help you get started with Actions

name: Official Gradle Wrapper Validation Action

on: [push, pull_request]

jobs:
  wrapper-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
        with:
          allow-snapshots: true
